# Snowflake Connection Configuration
[connections.snowflake]
account = "pm22530.us-east4.gcp"
user = "geekogenius"
password = "YxGvRk3mNpQzWa"
database = "ASN"
schema = "PUBLIC"
warehouse = "COMPUTE_WH"
role = "PUBLIC"

# Application Password
APP_PASSWORD = "dxt(Kl='1]87"

# Optional: OpenAI API Key (if you want to use OpenAI backup)
# OPENAI_API_KEY = "your-openai-api-key-here"
